# Generated by Django 4.1.3 on 2022-11-14 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecretSantaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecretSantaApp.participants')),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieve', to='SecretSantaApp.participants')),
            ],
        ),
    ]
